StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{596B48404F32F174}" {
   Id "ODIN-EditableEntity_AIWaypoint_Cycle_Name"
   Target_en_us "CYCLE"
   Target_fr_fr "RÉITÉRER"
   Target_it_it "CICLICO"
   Target_de_de "WIEDERHOLEN"
   Target_es_es "CICLO"
   Target_cs_cz "OPAKUJ"
   Target_pl_pl "PĘTLA"
   Target_ru_ru "ЗАЦИКЛИТЬ"
   Target_ja_jp "サイクル"
   Target_ko_kr "순환"
   Target_pt_br "PASSAR"
   Target_zh_cn "廻旋"
   MaxLength 0
   Modified 1501702822
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{5982226183CBA7D1}" {
   Id "ODIN-Editor_Attribute_EnableDamage_Name"
   Target_en_us "Enable damage"
   Target_fr_fr "Activer dégâts"
   Target_it_it "Abilita danno"
   Target_de_de "Schaden ermöglichen"
   Target_es_es "Activar daño"
   Target_cs_cz "Povolit poškození"
   Target_pl_pl "Włącz uszkodzenia"
   Target_ru_ru "Включить урон"
   Target_ja_jp "ダメージを有効"
   Target_ko_kr "피해 사용"
   Target_pt_br "Permitir dano"
   Target_zh_cn "启用损害"
   Modified 1501702727
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596C104FE13B959E}" {
   Id "ODIN-Editor_Attribute_Formation_Column_Name"
   Target_en_us "Column"
   Target_fr_fr "Colonne"
   Target_it_it "Colonna"
   Target_de_de "Kolonne"
   Target_es_es "Columna"
   Target_cs_cz "Zástup"
   Target_pl_pl "Kolumna"
   Target_ru_ru "Колонна"
   Target_ja_jp "縦隊"
   Target_ko_kr "종대"
   Target_pt_br "Coluna"
   Target_zh_cn "縱隊"
   Modified 1500259162
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596C104FE79A6382}" {
   Id "ODIN-Editor_Attribute_Formation_Line_Name"
   Target_en_us "Line"
   Target_fr_fr "Ligne"
   Target_it_it "Linea"
   Target_de_de "Reihe"
   Target_es_es "Línea"
   Target_cs_cz "Rojnice"
   Target_pl_pl "Linia"
   Target_ru_ru "Линия"
   Target_ja_jp "横隊"
   Target_ko_kr "횡대"
   Target_pt_br "Linha"
   Target_zh_cn "橫列"
   Modified 1500259131
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596B4845FA273D9B}" {
   Id "ODIN-Editor_Attribute_Formation_Name"
   Target_en_us "Formation"
   Target_fr_fr "Formation"
   Target_it_it "Formazione"
   Target_de_de "Formation"
   Target_es_es "Formación"
   Target_cs_cz "Formace"
   Target_pl_pl "Szyk"
   Target_ru_ru "Боевой порядок"
   Target_ja_jp "隊形"
   Target_ko_kr "대형"
   Target_pt_br "Formação"
   Target_zh_cn "隊形"
   MaxLength 0
   Modified 1501702812
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596C104FE5B1F23C}" {
   Id "ODIN-Editor_Attribute_Formation_StaggeredColumn_Name"
   Target_en_us "Staggered Col."
   Target_fr_fr "Col. décalée"
   Target_it_it "Col. frammentata"
   Target_de_de "Gestaffelte Kol."
   Target_es_es "Col. escalonada"
   Target_cs_cz "Dvojstup"
   Target_pl_pl "Kol. rozproszona"
   Target_ru_ru "Колонна в шахматном порядке"
   Target_ja_jp "千鳥型縦隊"
   Target_ko_kr "교차 종대"
   Target_pt_br "Coluna alternada"
   Target_zh_cn "交錯縱隊"
   Modified 1500259312
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596C104FDA05C8BC}" {
   Id "ODIN-Editor_Attribute_Formation_Wedge_Name"
   Target_en_us "Wedge"
   Target_fr_fr "Coin"
   Target_it_it "Cuneo"
   Target_de_de "Keil"
   Target_es_es "Cuña"
   Target_cs_cz "Klín"
   Target_pl_pl "Strzała"
   Target_ru_ru "Клин"
   Target_ja_jp "くさび隊形"
   Target_ko_kr "설형"
   Target_pt_br "Strzała"
   Target_zh_cn "楔形"
   Modified 1500258951
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596B4845144D7E85}" {
   Id "ODIN-Editor_Attribute_Skill_Name"
   Target_en_us "Skill"
   Target_fr_fr "Compétence"
   Target_it_it "Abilità"
   Target_de_de "Fähigkeit"
   Target_es_es "Habilidad"
   Target_cs_cz "Schopnost"
   Target_pl_pl "Wyszkolenie"
   Target_ru_ru "Навык"
   Target_ja_jp "スキル"
   Target_ko_kr "기술"
   Target_pt_br "Habilidade"
   Target_zh_cn "技能"
   MaxLength 0
   Modified 1501702797
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596D5D1218512832}" {
   Id "ODIN-Editor_Attribute_Stance_Crouch_Name"
   Target_en_us "Crouch"
   Target_fr_fr "Accroupi"
   Target_it_it "Accovacciato"
   Target_de_de "Ducken"
   Target_es_es "Agachado"
   Target_cs_cz "Zakleknout"
   Target_pl_pl "Przykucnięta"
   Target_ru_ru "Присесть"
   Target_ja_jp "屈む"
   Target_ko_kr "앉기"
   Target_pt_br "Agachado"
   Target_zh_cn "蹲伏"
   Modified 1500346957
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596D5D1217832506}" {
   Id "ODIN-Editor_Attribute_Stance_Name"
   Target_en_us "Stance"
   Target_fr_fr "Position"
   Target_it_it "Posizione"
   Target_de_de "Haltung"
   Target_es_es "Postura"
   Target_cs_cz "Postawa"
   Target_pl_pl "Postawa"
   Target_ru_ru "Стойка"
   Target_ja_jp "体勢"
   Target_ko_kr "자세"
   Target_pt_br "Postura"
   Target_zh_cn "戰鬥態勢"
   Modified 1500347013
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596D5D121A19DB22}" {
   Id "ODIN-Editor_Attribute_Stance_Prone_Name"
   Target_en_us "Prone"
   Target_fr_fr "À plat ventre"
   Target_it_it "Prono"
   Target_de_de "Hinlegen"
   Target_es_es "Tumbado"
   Target_cs_cz "Zalehnout"
   Target_pl_pl "Leżąca"
   Target_ru_ru "Лежа"
   Target_ja_jp "うつ伏せ"
   Target_ko_kr "엎드려 쏴"
   Target_pt_br "Deitado"
   Target_zh_cn "臥倒"
   Modified 1500346807
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{596D5D121F2C8BE0}" {
   Id "ODIN-Editor_Attribute_Stance_Stand_Name"
   Target_en_us "Stand"
   Target_fr_fr "Debout"
   Target_it_it "In piedi"
   Target_de_de "Aufstehen"
   Target_es_es "De pie"
   Target_cs_cz "Stát"
   Target_pl_pl "Stojąca"
   Target_ru_ru "Стоять"
   Target_ja_jp "立て"
   Target_ko_kr "선 자세"
   Target_pt_br "Em pé"
   Target_zh_cn "站起"
   Modified 1500346765
   Author "Kex"
   LastChanged "Kex"
  }
  CustomStringTableItem "{598222625B2CFC35}" {
   Id "ODIN-Editor_ContextAction_DeleteAllDead_Name"
   Target_en_us "Delete all corpses"
   Target_fr_fr "Effacer tous les corps"
   Target_de_de "Lösche alle Leichen"
   Modified 1501702516
   Author "Kex"
   LastChanged "Kex"
  }
 }
}