StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62B6A6C2A9CEE7F3}" {
   Id "GME-ActionList_AddGarrison_Description"
   Target_en_us "Spawn units to garrison the building"
   Target_de_de "Erstelle Einheiten, die das Gebäude besetzen"
   Modified 1656171603
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62B6A6C15778E1BB}" {
   Id "GME-ActionList_AddGarrison_Name"
   Target_en_us "Add Garrison"
   Target_de_de "Besaztung hinzufügen"
   Modified 1656171438
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{5DC552DCD58C02A3}" {
   Id "GME-ActionList_TeleportToSquadmate_Description"
   Target_en_us "Teleport unit to one of its squadmates"
   Target_fr_fr "Téléporter l'unité à l'un de ses coéquipiers"
   Target_it_it "Teletrasporta l'unità a uno dei suoi compagni di squadra"
   Target_de_de "Teleportiere die Einheit zu einem seiner Kameraden"
   Target_es_es "Unidad de teletransporte a uno de sus compañeros de escuadrón"
   Target_cs_cz "Teleportujte jednotku k jednomu z jejích spolubojovníci"
   Target_pl_pl "Teleportuj jednostkę do jednego z członków jej drużyny"
   Target_ru_ru "Телепортировать юнит к одному из его товарищей по отряду"
   Target_ja_jp "ユニットを分隊メンバーの一人にテレポートする"
   Target_ko_kr "유닛을 분대원 중 한 명에게 텔레포트합니다."
   Target_zh_cn "将单位传送至其一名队员处"
   Modified 1575019898
   Author "crow"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5DC552DCFF58F14E}" {
   Id "GME-ActionList_TeleportToSquadmate_Name"
   Target_en_us "Teleport To Squadmate"
   Target_fr_fr "Téléportation vers un coéquipier"
   Target_it_it "Teletrasporta al compagno di squadra"
   Target_de_de "Zum Kameraden teleportieren"
   Target_es_es "Teletransportarse a compañero de escuadrón"
   Target_cs_cz "Teleportujte se ke spolubojovníci"
   Target_pl_pl "Teleportuj się do członka drużyny"
   Target_ru_ru "Телепортироваться к товарищу по отряду"
   Target_ja_jp "分隊へテレポート"
   Target_ko_kr "분대원에게 텔레포트"
   Target_zh_cn "传送至队友"
   Modified 1575019335
   Author "crow"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5D19597480C381A5}" {
   Id "GME-Editor_Attribute_CompletionRadius_Name"
   Target_en_us "Completion radius"
   Target_en_us_edited ""
   Target_fr_fr "Radio de consecución"
   Target_it_it "Raggio di completamento"
   Target_de_de "Abschlussradius"
   Target_es_es "Radio de consecución"
   Target_cs_cz "Poloměr dokončení"
   Target_pl_pl "Promień zaliczenia"
   Target_ru_ru "Радиус завершения"
   Target_ja_jp "完了範囲"
   Target_ko_kr "완료 반경"
   Target_pt_br "Raio de posicionamento"
   Target_zh_cn "完成半徑"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C3844A}" {
   Id "GME-Editor_Attribute_CompletionType_All_Name"
   Target_en_us "All"
   Target_en_us_edited ""
   Target_fr_fr "Tous"
   Target_it_it "Tutti"
   Target_de_de "Alle"
   Target_es_es "Todo"
   Target_cs_cz "Všichni"
   Target_pl_pl "Wszyscy"
   Target_ru_ru "Все"
   Target_ja_jp "すべて"
   Target_ko_kr "전원"
   Target_pt_br "Todos"
   Target_zh_cn "全部"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38505}" {
   Id "GME-Editor_Attribute_CompletionType_Any_Name"
   Target_en_us "Any"
   Target_en_us_edited ""
   Target_fr_fr "Quelconque"
   Target_it_it "Qualsiasi"
   Target_de_de "Irgendeiner"
   Target_es_es "Cualquiera"
   Target_cs_cz "Jakýkoliv"
   Target_pl_pl "Dowolne"
   Target_ru_ru "Любой"
   Target_ja_jp "任意"
   Target_ko_kr "누구나"
   Target_pt_br "Qualquer"
   Target_zh_cn "任意"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C386CB}" {
   Id "GME-Editor_Attribute_CompletionType_Leader_Name"
   Target_en_us "Leader"
   Target_en_us_edited ""
   Target_fr_fr "Chef"
   Target_it_it "Capo"
   Target_de_de "Anführer"
   Target_es_es "Líder"
   Target_cs_cz "Velitel"
   Target_pl_pl "Dowódca"
   Target_ru_ru "Лидер"
   Target_ja_jp "リーダー"
   Target_ko_kr "지휘관"
   Target_pt_br "Líder"
   Target_zh_cn "隊長"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C3879E}" {
   Id "GME-Editor_Attribute_CompletionType_Name"
   Target_en_us "Completion type"
   Target_en_us_edited ""
   Target_fr_fr "Type de consecución"
   Target_it_it ""
   Target_de_de "Abschlusstyp"
   Target_es_es ""
   Target_cs_cz ""
   Target_pl_pl ""
   Target_ru_ru ""
   Target_ja_jp ""
   Target_ko_kr ""
   Target_pt_br ""
   Target_zh_cn ""
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C3895E}" {
   Id "GME-Editor_Attribute_EnableDamage_Name"
   Target_en_us "Enable damage"
   Target_en_us_edited ""
   Target_fr_fr "Activer dégâts"
   Target_it_it "Abilita danno"
   Target_de_de "Schaden ermöglichen"
   Target_es_es "Activar daño"
   Target_cs_cz "Povolit poškození"
   Target_pl_pl "Włącz uszkodzenia"
   Target_ru_ru "Включить урон"
   Target_ja_jp "ダメージを有効"
   Target_ko_kr "피해 사용"
   Target_pt_br "Permitir dano"
   Target_zh_cn "启用损害"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38A06}" {
   Id "GME-Editor_Attribute_Formation_Column_Name"
   Target_en_us "Column"
   Target_en_us_edited ""
   Target_fr_fr "Colonne"
   Target_it_it "Colonna"
   Target_de_de "Kolonne"
   Target_es_es "Columna"
   Target_cs_cz "Zástup"
   Target_pl_pl "Kolumna"
   Target_ru_ru "Колонна"
   Target_ja_jp "縦隊"
   Target_ko_kr "종대"
   Target_pt_br "Coluna"
   Target_zh_cn "縱隊"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38BC3}" {
   Id "GME-Editor_Attribute_Formation_Line_Name"
   Target_en_us "Line"
   Target_en_us_edited ""
   Target_fr_fr "Ligne"
   Target_it_it "Linea"
   Target_de_de "Reihe"
   Target_es_es "Línea"
   Target_cs_cz "Rojnice"
   Target_pl_pl "Linia"
   Target_ru_ru "Линия"
   Target_ja_jp "横隊"
   Target_ko_kr "횡대"
   Target_pt_br "Linha"
   Target_zh_cn "橫列"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38C9C}" {
   Id "GME-Editor_Attribute_Formation_Name"
   Target_en_us "Formation"
   Target_en_us_edited ""
   Target_fr_fr "Formation"
   Target_it_it "Formazione"
   Target_de_de "Formation"
   Target_es_es "Formación"
   Target_cs_cz "Formace"
   Target_pl_pl "Szyk"
   Target_ru_ru "Боевой порядок"
   Target_ja_jp "隊形"
   Target_ko_kr "대형"
   Target_pt_br "Formação"
   Target_zh_cn "隊形"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38E30}" {
   Id "GME-Editor_Attribute_Formation_StaggeredColumn_Name"
   Target_en_us "Staggered Col."
   Target_en_us_edited ""
   Target_fr_fr "Col. décalée"
   Target_it_it "Col. frammentata"
   Target_de_de "Gestaffelte Kol."
   Target_es_es "Col. escalonada"
   Target_cs_cz "Dvojstup"
   Target_pl_pl "Kol. rozproszona"
   Target_ru_ru "Колонна в шахматном порядке"
   Target_ja_jp "千鳥型縦隊"
   Target_ko_kr "교차 종대"
   Target_pt_br "Coluna alternada"
   Target_zh_cn "交錯縱隊"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38F0D}" {
   Id "GME-Editor_Attribute_Formation_Wedge_Name"
   Target_en_us "Wedge"
   Target_en_us_edited ""
   Target_fr_fr "Coin"
   Target_it_it "Cuneo"
   Target_de_de "Keil"
   Target_es_es "Cuña"
   Target_cs_cz "Klín"
   Target_pl_pl "Strzała"
   Target_ru_ru "Клин"
   Target_ja_jp "くさび隊形"
   Target_ko_kr "설형"
   Target_pt_br "Strzała"
   Target_zh_cn "楔形"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62AC0332176045C1}" {
   Id "GME-Editor_Attribute_GlobalSkill_Description"
   Target_en_us "Global skill applied to all current and future AI units."
   Target_de_de "Globale Fähikgeit für alle momentanen und zukünftigen KI Einheiten."
   Modified 1655442170
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62AC0332B5EAA317}" {
   Id "GME-Editor_Attribute_GlobalSkill_Name"
   Target_en_us "Global skill"
   Target_de_de "Globale Fähigkeit"
   Modified 1655442624
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62A6ECE007097ABC}" {
   Id "GME-Editor_Attribute_IntelContent_Name"
   Target_en_us "Intel content"
   Target_de_de "Hinweisinhalt"
   Modified 1655109673
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62A6ECE003544E7E}" {
   Id "GME-Editor_Attribute_IntelTitel_Name"
   Target_en_us "Intel title"
   Target_de_de "Hinweistitel"
   Modified 1656551081
   Author "Kexanone"
   LastChanged "crow"
  }
  CustomStringTableItem "{62AB6754F6815523}" {
   Id "GME-Editor_Attribute_Skill_CYLON_Name"
   Target_en_us "Cylon"
   Target_de_de "Zylon"
   Modified 1655402702
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62AC0335B164BC43}" {
   Id "GME-Editor_Attribute_Skill_Description"
   Target_en_us "Skill of the AI"
   Target_de_de "Fähigkeit der KI"
   Modified 1655442193
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62AB6754F218EBFA}" {
   Id "GME-Editor_Attribute_Skill_EXPERT_Name"
   Target_en_us "Expert"
   Target_de_de "Experte"
   Modified 1655402571
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{5D19597480C3F0C8}" {
   Id "GME-Editor_Attribute_Skill_Name"
   Target_en_us "Skill"
   Target_en_us_edited ""
   Target_fr_fr "Compétence"
   Target_it_it "Abilità"
   Target_de_de "Fähigkeit"
   Target_es_es "Habilidad"
   Target_cs_cz "Schopnost"
   Target_pl_pl "Wyszkolenie"
   Target_ru_ru "Навык"
   Target_ja_jp "スキル"
   Target_ko_kr "기술"
   Target_pt_br "Habilidade"
   Target_zh_cn "技能"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62AC0333E8DB461C}" {
   Id "GME-Editor_Attribute_Skill_NONE_Name"
   Target_en_us "Not set"
   Target_de_de "Nicht gesetzt"
   Modified 1655441434
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62AB6754CDEE5CBB}" {
   Id "GME-Editor_Attribute_Skill_REGULAR_Name"
   Target_en_us "Regular"
   Target_de_de "Regulär"
   Modified 1655402715
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62AB6754D57986EC}" {
   Id "GME-Editor_Attribute_Skill_ROOKIE_Name"
   Target_en_us "Rookie"
   Target_de_de "Anfänger"
   Modified 1655402780
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62AB6754FE4A9F26}" {
   Id "GME-Editor_Attribute_Skill_VETERAN_Name"
   Target_en_us "Veteran"
   Target_de_de "Veteran"
   Modified 1655402789
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{5D19597480C3F188}" {
   Id "GME-Editor_Attribute_Stance_Crouch_Name"
   Target_en_us "Crouch"
   Target_en_us_edited ""
   Target_fr_fr "Accroupi"
   Target_it_it "Accovacciato"
   Target_de_de "Ducken"
   Target_es_es "Agachado"
   Target_cs_cz "Zakleknout"
   Target_pl_pl "Przykucnięta"
   Target_ru_ru "Присесть"
   Target_ja_jp "屈む"
   Target_ko_kr "앉기"
   Target_pt_br "Agachado"
   Target_zh_cn "蹲伏"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C3F327}" {
   Id "GME-Editor_Attribute_Stance_Name"
   Target_en_us "Stance"
   Target_en_us_edited ""
   Target_fr_fr "Position"
   Target_it_it "Posizione"
   Target_de_de "Haltung"
   Target_es_es "Postura"
   Target_cs_cz "Postawa"
   Target_pl_pl "Postawa"
   Target_ru_ru "Стойка"
   Target_ja_jp "体勢"
   Target_ko_kr "자세"
   Target_pt_br "Postura"
   Target_zh_cn "戰鬥態勢"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C3F486}" {
   Id "GME-Editor_Attribute_Stance_Prone_Name"
   Target_en_us "Prone"
   Target_en_us_edited ""
   Target_fr_fr "À plat ventre"
   Target_it_it "Prono"
   Target_de_de "Hinlegen"
   Target_es_es "Tumbado"
   Target_cs_cz "Zalehnout"
   Target_pl_pl "Leżąca"
   Target_ru_ru "Лежа"
   Target_ja_jp "うつ伏せ"
   Target_ko_kr "엎드려 쏴"
   Target_pt_br "Deitado"
   Target_zh_cn "臥倒"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C3EEB2}" {
   Id "GME-Editor_Attribute_Stance_Stand_Name"
   Target_en_us "Stand"
   Target_en_us_edited ""
   Target_fr_fr "Debout"
   Target_it_it "In piedi"
   Target_de_de "Aufstehen"
   Target_es_es "De pie"
   Target_cs_cz "Stát"
   Target_pl_pl "Stojąca"
   Target_ru_ru "Стоять"
   Target_ja_jp "立て"
   Target_ko_kr "선 자세"
   Target_pt_br "Em pé"
   Target_zh_cn "站起"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{5D19597480C38375}" {
   Id "GME-Editor_Attribute_ValueFormatting_Length"
   Target_en_us "%1 m"
   Target_en_us_edited ""
   Target_fr_fr "%1 m"
   Target_it_it "%1 m"
   Target_de_de "%1 m"
   Target_es_es "%1 m"
   Target_cs_cz "%1 m"
   Target_pl_pl "%1 m"
   Target_ru_ru "%1 m"
   Target_ja_jp "%1 m"
   Target_ko_kr "%1 m"
   Target_pt_br "%1 m"
   Target_zh_cn "%1 米"
   Target_uk_ua "%1 m"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1656230612
   Author "Kexanone"
   LastChanged "Kexanone"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62071BC2FE856882}" {
   Id "GME-Editor_Attribute_ValueFormatting_Speed"
   Target_en_us "%1 km/h"
   Target_fr_fr "%1 km/h"
   Target_it_it "%1 km/h"
   Target_de_de "%1 km/h"
   Target_es_es "%1 km/h"
   Target_cs_cz "%1 km/h"
   Target_pl_pl "%1 km/h"
   Target_ru_ru "%1 km/h"
   Target_ja_jp "%1 km/h"
   Target_ko_kr "%1 km/h"
   Target_pt_br "%1 km/h"
   Target_zh_cn "%1 km/h"
   Target_uk_ua "%1 km/h"
   Modified 1644635353
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{5D955C2079184639}" {
   Id "GME-Editor_Attribute_VisibilityToggle_Name"
   Target_en_us "Visibility"
   Target_fr_fr "Visibilité"
   Target_it_it "Visibilità"
   Target_de_de "Sichtbarkeit"
   Target_es_es "Visibilidad"
   Target_cs_cz "Viditelnost"
   Target_pl_pl "Widoczność"
   Target_ru_ru "Видимость"
   Target_ja_jp "可視性"
   Target_ko_kr "가시거리"
   Target_pt_br "Visibilidade"
   Target_zh_cn "可見度"
   Modified 1575018999
   Author "crow"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5D19597480C380D1}" {
   Id "GME-Editor_AttributeCategory_Waypoint_Name"
   Target_en_us "Waypoint"
   Target_en_us_edited ""
   Target_fr_fr "Point de passage"
   Target_it_it "Destinazione"
   Target_de_de "Wegpunkt"
   Target_es_es "unto de referencia"
   Target_cs_cz "Bod trasy"
   Target_pl_pl "unkt trasy"
   Target_ru_ru "Точка маршрута"
   Target_ja_jp "ウェイポイント"
   Target_ko_kr "경유지"
   Target_pt_br "Ponto de rota"
   Target_zh_cn "路点"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1561942876
   Author "Kex"
   LastChanged "crow"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{6207444BFA04A823}" {
   Id "GME-Editor_ContentBrowser_Filter_AI_Name"
   Target_en_us "AI"
   Target_de_de "KI"
   Modified 1644643579
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62072CE78F00B469}" {
   Id "GME-Editor_ContentBrowser_Filter_REINFORCEMENTS_Name"
   Target_en_us "Reinforcements"
   Target_de_de "Verstärkungen"
   Modified 1644643107
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62072CE8E3670EA2}" {
   Id "GME-Editor_ContentBrowser_FilterCategory_MODULETYPE_Name"
   Target_en_us "Module Type"
   Target_de_de "Modultyp"
   Modified 1644639744
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62B6A6C23197C040}" {
   Id "GME-Editor_ContentBrowser_Title_ChooseGarrison"
   Target_en_us "Choose garrison"
   Target_de_de "Besatzung auswählen"
   Modified 1656171782
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{61FF20CD7A430C94}" {
   Id "GME-Modules_AmbientFlyby_Mi8MT_name"
   Target_en_us "Ambient Mi-8MT Flyby"
   Target_de_de "Atmosphärischer Vorbeiflug eines Mi-9MT"
   Modified 1644113190
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{61FF20CD461AC2BD}" {
   Id "GME-Modules_AmbientFlyby_UH1H_name"
   Target_en_us "Ambient UH-1H Flyby"
   Target_de_de "Atmosphärischer Vorbeiflug eines UH-1H"
   Modified 1644113187
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62071BC43A365B6C}" {
   Id "GME-Modules_Attribute_Height_Name"
   Target_en_us "Height"
   Target_de_de "Höhe"
   Modified 1644634787
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62055062957C227C}" {
   Id "GME-Modules_Attribute_RTBAndDespawn_Name"
   Target_en_us "RTB and Despawn"
   Target_it_it "Indietro ed elimina"
   Target_de_de "Zurück und Löschen"
   Target_pl_pl "róc do bazy i despawnuj"
   Target_ja_jp "RTB と削除"
   Target_ko_kr "귀환 후 삭제"
   Target_zh_cn "返回並刪除"
   Modified 1655255408
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62071BC4205E761B}" {
   Id "GME-Modules_Attribute_Speed_Name"
   Target_en_us "Speed"
   Target_de_de "Tempo"
   Modified 1644635003
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62071BC42E178789}" {
   Id "GME-Modules_Attribute_StartDistance_Name"
   Target_en_us "Start distance"
   Target_de_de "Startdistanz"
   Modified 1644634991
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{620550636AF46B2D}" {
   Id "GME-Modules_Attribute_StayAtLZ_Name"
   Target_en_us "Stay at LZ"
   Target_it_it "Soggiorna a LZ"
   Target_de_de "Bei LZ verbleiben"
   Target_pl_pl "Pozostań na LZ"
   Target_ja_jp "LZ で待機"
   Target_ko_kr "LZ에 머물르기"
   Target_zh_cn "留在LZ"
   Modified 1644515962
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62055062CA08FD71}" {
   Id "GME-Modules_Attribute_VehicleBehavior_Name"
   Target_en_us "Vehicle behaviour"
   Target_it_it "Comportamento del veicolo"
   Target_de_de "Fahrzeugverhalten"
   Target_pl_pl "Pozostań na LZ"
   Target_ja_jp "車両の挙動"
   Target_ko_kr "차량 행동"
   Target_zh_cn "載具行為"
   Modified 1644516114
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6202E59FD262279C}" {
   Id "GME-Modules_LZ_name"
   Target_en_us "LZ"
   Target_de_de "LZ"
   Target_pl_pl "LZ (Strefa lądowania)"
   Modified 1644521376
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6202E59FDCD14A02}" {
   Id "GME-Modules_RallyPoint_name"
   Target_en_us "Rally Point"
   Target_de_de "Sammelpunkt"
   Target_pl_pl "Punkt spotkania"
   Modified 1644358788
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{6202F0DA1EEF77C4}" {
   Id "GME-Modules_SpawnReinforcements_name"
   Target_en_us "Spawn Reinforcements"
   Target_it_it "Genera rinforzi"
   Target_de_de "Erstelle Verstärkung"
   Target_pl_pl "Spawnuj Wzmocnienia (posiłki)"
   Target_ja_jp "増援生成"
   Target_ko_kr "증원군 소환"
   Target_zh_cn "生成增援"
   Modified 1644360233
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{62A6ECE1437D6A68}" {
   Id "GME-Notification_PICKED_UP_ITEM"
   Target_en_us "%1 picked up %2"
   Target_de_de "%1 hat %2 aufgelesen"
   Modified 1655109533
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{620508C43021603F}" {
   Id "GME-Notification_PLACE_PREFAB_FIRST"
   Target_en_us "Place %1 first!"
   Target_de_de "Plaziere %1 zuerst!"
   Modified 1644511846
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{5DC552DA2913D62A}" {
   Id "GME-UI_Listbox_OnCancel"
   Target_en_us "Cancel"
   Target_fr_fr "Annuler"
   Target_it_it "Annulla"
   Target_de_de "Abbrechen"
   Target_es_es "Cancelar"
   Target_cs_cz "Zrušit"
   Target_pl_pl "Anuluj"
   Target_ru_ru "Отмена"
   Target_ja_jp "キャンセル"
   Target_ko_kr "취소"
   Target_pt_br "Cancelar"
   Target_zh_cn "取消"
   Modified 1655266293
   Author "crow"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{5DC552DA2D2CBC68}" {
   Id "GME-UI_Listbox_OnConfirm"
   Target_en_us "Confirm"
   Target_fr_fr "Confirmer"
   Target_it_it "Confermar"
   Target_de_de "Bestätigen"
   Target_es_es "Confirmar"
   Target_cs_cz "Potvrdit"
   Target_pl_pl "Potwierdź"
   Target_ru_ru "Подтвердить"
   Target_ja_jp "確定"
   Target_ko_kr "확인"
   Target_pt_br "Confirmar"
   Target_zh_cn "確認"
   Modified 1575018908
   Author "crow"
   LastChanged "kexanone"
  }
 }
}