PersistenceSystemConfig : "{BEFFBD9A87620F23}Configs/Systems/Persistence/BaseSetup.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Player {
     Configurations {
      EntityPersistenceConfig "{64ECE6462993EA13}" {
       ComponentSerializers {
        GME_HitZoneContainerComponentSerializer "{64EACDEFFE4BE0BD}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup AI {
     Configurations {
      EntityPersistenceConfig "{64EACAC5BFDB31EC}" {
       ComponentSerializers {
        GME_HitZoneContainerComponentSerializer "{64EACDEFFE4BE0BD}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup Items {
     Configurations {
      EntityPersistenceConfig "{64CAFB94F1A3338C}" {
       ComponentSerializers {
        GME_IntelComponentSerializer "{66B530F7B9DBB2DA}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup Vehicles {
     Configurations {
      EntityPersistenceConfig "{64C6B4937723DA61}" {
       ComponentSerializers {
        GME_HitZoneContainerComponentSerializer "{64C6AEE093D101FA}" {
        }
       }
      }
      EntityPersistenceConfig "{6660869EC5E7F4C2}" {
       ComponentSerializers {
        GME_HitZoneContainerComponentSerializer "{64C6AEE093D101FA}" {
        }
       }
      }
      EntityPersistenceConfig "{64EE8D74EB8192BA}" {
       ComponentSerializers {
        GME_HitZoneContainerComponentSerializer "{64C6AEE093D101FA}" {
        }
       }
      }
     }
    }
   }
  }
 }
}