PersistenceSystemConfig : "{8532E1DD4E714D95}Configs/Systems/Persistence/Mission.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Player {
     Configurations {
      EntityPersistenceConfig "{64ECE6462993EA13}" {
       ComponentSerializers {
        SCR_EditableEntityComponentSerializer "{66B54665D53A79D8}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup AI {
     Configurations {
      EntityPersistenceConfig "{64EACAC5BFDB31EC}" {
       ComponentSerializers {
        SCR_EditableEntityComponentSerializer "{66B54665CE3322EE}" {
        }
       }
      }
     }
    }
    PersistenceConfigGroup Misc {
     Configurations {
      EntityPersistenceConfig "{66B5466550722E1E}" {
       Rule PrefabPersistenceConfigRule "{66B546654BBE47A1}" {
        Prefabs {
         "{57C4079FD5B14D31}PrefabsEditable/Modules/E_GME_Modules_Base.et"
        }
       }
       Collection "{6624C4351F719B74}"
       EntitySerializer GenericEntitySerializer "{66B546654612D3DE}" {
       }
       ComponentSerializers {
        GME_Modules_EditablePointComponentSerializer "{66B546649E7ECDB1}" {
        }
       }
      }
     }
    }
   }
  }
 }
}